services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG:-latest}
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      - SPRINGDOC_SERVER_URL=/

      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_MILLISECONDS=${JWT_ACCESS_TOKEN_EXPIRATION_MILLISECONDS}

      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - KAKAO_MAP_JS_KEY=${KAKAO_MAP_JS_KEY}

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - routie-net
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - routie-net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      app:
        condition: service_started
    networks:
      - routie-net
    restart: unless-stopped

networks:
  routie-net:
    driver: bridge

volumes:
  mysql-data: